export const lessonStructure = {
  fundamentals: {
    title: 'Fundamentals',
    description: 'Master the essential building blocks of sign language, including the alphabet and basic gestures.',
    icon: '/SVGIcons/Fundamentals/alphabet.svg',
    gradient: 'linear-gradient(135deg, #43cea2 0%, #185a9d 100%)',
    totalSigns: 54,
    subCategories: {
      alphabet: {
        title: 'Alphabet & Fingerspelling',
        description: 'Learn the FSL alphabet and how to fingerspell words',
        icon: '/SVGIcons/Fundamentals/alphabet.svg',
        content: [ 
          { id: 'a', title: 'Letter A', video: '/FSLAssetsVideos/Fundamentals/alphabet/A.mp4' },
          { id: 'b', title: 'Letter B', video: '/FSLAssetsVideos/Fundamentals/alphabet/B.mp4' },
          { id: 'c', title: 'Letter C', video: '/FSLAssetsVideos/Fundamentals/alphabet/C.mp4' },
          { id: 'd', title: 'Letter D', video: '/FSLAssetsVideos/Fundamentals/alphabet/D.mp4' },
          { id: 'e', title: 'Letter E', video: '/FSLAssetsVideos/Fundamentals/alphabet/E.mp4' },
          { id: 'f', title: 'Letter F', video: '/FSLAssetsVideos/Fundamentals/alphabet/F.mp4' },
          { id: 'g', title: 'Letter G', video: '/FSLAssetsVideos/Fundamentals/alphabet/G.mp4' },
          { id: 'h', title: 'Letter H', video: '/FSLAssetsVideos/Fundamentals/alphabet/H.mp4' },
          { id: 'i', title: 'Letter I', video: '/FSLAssetsVideos/Fundamentals/alphabet/I.mp4' },
          { id: 'j', title: 'Letter J', video: '/FSLAssetsVideos/Fundamentals/alphabet/J.mp4' },
          { id: 'k', title: 'Letter K', video: '/FSLAssetsVideos/Fundamentals/alphabet/K.mp4' },
          { id: 'l', title: 'Letter L', video: '/FSLAssetsVideos/Fundamentals/alphabet/L.mp4' },
          { id: 'm', title: 'Letter M', video: '/FSLAssetsVideos/Fundamentals/alphabet/M.mp4' },
          { id: 'n', title: 'Letter N', video: '/FSLAssetsVideos/Fundamentals/alphabet/N.mp4' },
          { id: 'ñ', title: 'Letter Ñ', video: '/FSLAssetsVideos/Fundamentals/alphabet/Ñ.mp4' },
          { id: 'ng', title: 'Letter Ng', video: '/FSLAssetsVideos/Fundamentals/alphabet/Ng.mp4' },
          { id: 'o', title: 'Letter O', video: '/FSLAssetsVideos/Fundamentals/alphabet/O.mp4' },
          { id: 'p', title: 'Letter P', video: '/FSLAssetsVideos/Fundamentals/alphabet/P.mp4' },
          { id: 'q', title: 'Letter Q', video: '/FSLAssetsVideos/Fundamentals/alphabet/Q.mp4' },
          { id: 'r', title: 'Letter R', video: '/FSLAssetsVideos/Fundamentals/alphabet/R.mp4' },
          { id: 's', title: 'Letter S', video: '/FSLAssetsVideos/Fundamentals/alphabet/S.mp4' },
          { id: 't', title: 'Letter T', video: '/FSLAssetsVideos/Fundamentals/alphabet/T.mp4' },
          { id: 'u', title: 'Letter U', video: '/FSLAssetsVideos/Fundamentals/alphabet/U.mp4' },
          { id: 'v', title: 'Letter V', video: '/FSLAssetsVideos/Fundamentals/alphabet/V.mp4' },
          { id: 'w', title: 'Letter W', video: '/FSLAssetsVideos/Fundamentals/alphabet/W.mp4' },
          { id: 'x', title: 'Letter X', video: '/FSLAssetsVideos/Fundamentals/alphabet/X.mp4' },
          { id: 'y', title: 'Letter Y', video: '/FSLAssetsVideos/Fundamentals/alphabet/Y.mp4' },
          { id: 'z', title: 'Letter Z', video: '/FSLAssetsVideos/Fundamentals/alphabet/Z.mp4' }
        ]
      },
      numbers: {
        title: 'Numbers',
        description: 'Learn to sign numbers in FSL',
        icon: '/SVGIcons/Fundamentals/numbers.svg',
        content: [
          { id: '1', title: '1', video: '/FSLAssetsVideos/Fundamentals/numbers/1.mp4' },
          { id: '2', title: '2', video: '/FSLAssetsVideos/Fundamentals/numbers/2.mp4' },
          { id: '3', title: '3', video: '/FSLAssetsVideos/Fundamentals/numbers/3.mp4' },
          { id: '4', title: '4', video: '/FSLAssetsVideos/Fundamentals/numbers/4.mp4' },
          { id: '5', title: '5', video: '/FSLAssetsVideos/Fundamentals/numbers/5.mp4' },
          { id: '6', title: '6', video: '/FSLAssetsVideos/Fundamentals/numbers/6.mp4' },
          { id: '7', title: '7', video: '/FSLAssetsVideos/Fundamentals/numbers/7.mp4' },
          { id: '8', title: '8', video: '/FSLAssetsVideos/Fundamentals/numbers/8.mp4' },
          { id: '9', title: '9', video: '/FSLAssetsVideos/Fundamentals/numbers/9.mp4' },
          { id: '10', title: '10', video: '/FSLAssetsVideos/Fundamentals/numbers/10.mp4' },
          { id: '11', title: '11', video: '/FSLAssetsVideos/Fundamentals/numbers/11.mp4' },
          { id: '12', title: '12', video: '/FSLAssetsVideos/Fundamentals/numbers/12.mp4' },
          { id: '13', title: '13', video: '/FSLAssetsVideos/Fundamentals/numbers/13.mp4' },
          { id: '14', title: '14', video: '/FSLAssetsVideos/Fundamentals/numbers/14.mp4' },
          { id: '15', title: '15', video: '/FSLAssetsVideos/Fundamentals/numbers/15.mp4' },
          { id: '16', title: '16', video: '/FSLAssetsVideos/Fundamentals/numbers/16.mp4' },
          { id: '17', title: '17', video: '/FSLAssetsVideos/Fundamentals/numbers/17.mp4' },
          { id: '18', title: '18', video: '/FSLAssetsVideos/Fundamentals/numbers/18.mp4' },
          { id: '19', title: '19', video: '/FSLAssetsVideos/Fundamentals/numbers/19.mp4' },
          { id: '20', title: '20', video: '/FSLAssetsVideos/Fundamentals/numbers/20.mp4' },
          { id: '21', title: '21', video: '/FSLAssetsVideos/Fundamentals/numbers/21.mp4' },
          { id: '22', title: '22', video: '/FSLAssetsVideos/Fundamentals/numbers/22.mp4' },
          { id: '23', title: '23', video: '/FSLAssetsVideos/Fundamentals/numbers/23.mp4' },
          { id: '24', title: '24', video: '/FSLAssetsVideos/Fundamentals/numbers/24.mp4' },
          { id: '25', title: '25', video: '/FSLAssetsVideos/Fundamentals/numbers/25.mp4' },
          { id: '26', title: '26', video: '/FSLAssetsVideos/Fundamentals/numbers/26.mp4' },
          { id: '27', title: '27', video: '/FSLAssetsVideos/Fundamentals/numbers/27.mp4' },
          { id: '28', title: '28', video: '/FSLAssetsVideos/Fundamentals/numbers/28.mp4' },
          { id: '29', title: '29', video: '/FSLAssetsVideos/Fundamentals/numbers/29.mp4' },
          { id: '30', title: '30', video: '/FSLAssetsVideos/Fundamentals/numbers/30.mp4' },
          { id: '40', title: '40', video: '/FSLAssetsVideos/Fundamentals/numbers/40.mp4' },
          { id: '50', title: '50', video: '/FSLAssetsVideos/Fundamentals/numbers/50.mp4' },
          { id: '60', title: '60', video: '/FSLAssetsVideos/Fundamentals/numbers/60.mp4' },
          { id: '70', title: '70', video: '/FSLAssetsVideos/Fundamentals/numbers/70.mp4' },
          { id: '80', title: '80', video: '/FSLAssetsVideos/Fundamentals/numbers/80.mp4' },
          { id: '90', title: '90', video: '/FSLAssetsVideos/Fundamentals/numbers/90.mp4' },
          { id: '100', title: '100', video: '/FSLAssetsVideos/Fundamentals/numbers/100.mp4' },
          { id: '200', title: '200', video: '/FSLAssetsVideos/Fundamentals/numbers/200.mp4' },
          { id: '300', title: '300', video: '/FSLAssetsVideos/Fundamentals/numbers/300.mp4' },
          { id: '400', title: '400', video: '/FSLAssetsVideos/Fundamentals/numbers/400.mp4' },
          { id: '500', title: '500', video: '/FSLAssetsVideos/Fundamentals/numbers/500.mp4' },
          { id: '600', title: '600', video: '/FSLAssetsVideos/Fundamentals/numbers/600.mp4' },
          { id: '700', title: '700', video: '/FSLAssetsVideos/Fundamentals/numbers/700.mp4' },
          { id: '800', title: '800', video: '/FSLAssetsVideos/Fundamentals/numbers/800.mp4' },
          { id: '900', title: '900', video: '/FSLAssetsVideos/Fundamentals/numbers/900.mp4' },
          { id: '1000', title: '1000', video: '/FSLAssetsVideos/Fundamentals/numbers/1000.mp4' },
        ]
      },
      commonQuestions: {
        title: 'Common Questions',
        description: 'Essential questions for everyday conversations',
        icon: '/SVGIcons/Fundamentals/commonQuestions.svg',
        content: [
          { id: 'what-name', title: 'What is your name?', video: '/FSLAssetsVideos/Fundamentals/commonQuestion/Whatisyourname.mp4' },
          { id: 'how-are-you', title: 'How are you?', video: '/FSLAssetsVideos/Fundamentals/commonQuestion/Howareyou.mp4' },
          { id: 'where-live', title: 'Where do you live?', video: '/FSLAssetsVideos/Fundamentals/commonQuestion/Wheredoyoulive.mp4' },
          { id: 'how-old', title: 'How old are you?', video: '/FSLAssetsVideos/Fundamentals/commonQuestion/Howoldareyou.mp4' },
          { id: 'what-time', title: 'What time is it?', video: '/FSLAssetsVideos/Fundamentals/commonQuestion/Whattimeisit.mp4' },
          { id: 'do-understand', title: 'Do you understand?', video: '/FSLAssetsVideos/Fundamentals/commonQuestion/Doyouunderstand.mp4' },
          { id: 'where-from', title: 'Where are you from?', video: '/FSLAssetsVideos/Fundamentals/commonQuestion/Whereareyoufrom.mp4' },
          { id: 'can-help', title: 'Can you help me?', video: '/FSLAssetsVideos/Fundamentals/commonQuestion/Canyouhelpme.mp4' },
          { id: 'what-want', title: 'What do you want?', video: '/FSLAssetsVideos/Fundamentals/commonQuestion/Whatdoyouwant.mp4' },
        ]
      },
      simplePhrases: {
        title: 'Simple Phrases',
        description: 'Basic phrases for polite communication',
        icon: '/SVGIcons/Fundamentals/simplePhrases.svg',
        content: [
          { id: 'nice-meet', title: 'Nice to meet you', video: '/FSLAssetsVideos/Fundamentals/simplePhrases/Nicetomeetyou.mp4' },
          { id: 'thank-you', title: 'Thank you', video: '/FSLAssetsVideos/Fundamentals/simplePhrases/Thankyou.mp4' },
          { id: 'you-welcome', title: "You're welcome", video: '/FSLAssetsVideos/Fundamentals/simplePhrases/Yourewelcome.mp4' },
          { id: 'dont-understand', title: "I don't understand", video: '/FSLAssetsVideos/Fundamentals/simplePhrases/Idontunderstand.mp4' },
          { id: 'please', title: 'Please', video: '/FSLAssetsVideos/Fundamentals/simplePhrases/Please.mp4' },
          { id: 'sorry', title: 'Sorry', video: '/FSLAssetsVideos/Fundamentals/simplePhrases/Sorry.mp4' },
          { id: 'yes', title: 'Yes', video: '/FSLAssetsVideos/Fundamentals/simplePhrases/Yes.mp4' },
          { id: 'no', title: 'No', video: '/FSLAssetsVideos/Fundamentals/simplePhrases/No.mp4' },
        ]
      }, 
    }
  },
  everydayWords: {
    title: 'Everyday Words',
    description: 'Master the essential building blocks of sign language, including the alphabet and basic gestures."',
    icon: '/SVGIcons/EveryDayWords/greetingsPoliteExpressions.svg',
    gradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    totalSigns: 144,
    subCategories: {
      greetings: {
        title: 'Greetings & Polite Expressions',
        description: 'Greetings and polite expressions for daily use',
        icon: '/SVGIcons/EveryDayWords/greetingsPoliteExpressions.svg',
        content: [
          { id: 'hello', title: 'Hello', video: '/FSLAssetsVideos/EeveryDayWords/greetings&PoliteExpressions/Hello.mp4' },
          { id: 'good-morning', title: 'Good morning', video: '/FSLAssetsVideos/EeveryDayWords/greetings&PoliteExpressions/Goodmorning.mp4' },
          { id: 'good-afternoon', title: 'Good afternoon', video: '/FSLAssetsVideos/EeveryDayWords/greetings&PoliteExpressions/Goodafternoon.mp4' },
          { id: 'good-evening', title: 'Good evening', video: '/FSLAssetsVideos/EeveryDayWords/greetings&PoliteExpressions/Goodevening.mp4' },
          { id: 'good-night', title: 'Good night', video: '/FSLAssetsVideos/EeveryDayWords/greetings&PoliteExpressions/Goodnight.mp4' },
          { id: 'goodbye', title: 'Goodbye', video: '/FSLAssetsVideos/EeveryDayWords/greetings&PoliteExpressions/Goodbye.mp4' },
          { id: 'how-are-you', title: 'How are you?', video: '/FSLAssetsVideos/EeveryDayWords/greetings&PoliteExpressions/Howareyou.mp4' },
          { id: 'fine', title: 'Fine', video: '/FSLAssetsVideos/EeveryDayWords/greetings&PoliteExpressions/Fine.mp4' },
          { id: 'welcome', title: 'Welcome', video: '/FSLAssetsVideos/EeveryDayWords/greetings&PoliteExpressions/Welcome.mp4' },
        ]
      },
      daysMonths: {
        title: 'Days of the Week & Months',
        description: 'Days, months, and time expressions',
        icon: '/SVGIcons/EveryDayWords/daysWeeksMonths.svg',
        content: [
          { id: 'monday', title: 'Monday', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Monday.mp4' },
          { id: 'tuesday', title: 'Tuesday', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Tuesday.mp4' },
          { id: 'wednesday', title: 'Wednesday', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Wednesday.mp4' },
          { id: 'thursday', title: 'Thursday', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Thursday.mp4' },
          { id: 'friday', title: 'Friday', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Friday.mp4' },
          { id: 'saturday', title: 'Saturday', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Saturday.mp4' },
          { id: 'sunday', title: 'Sunday', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Sunday.mp4' },
          { id: 'january', title: 'January', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Months/Jan.mp4' },
          { id: 'february', title: 'February', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Months/Feb.mp4' },
          { id: 'march', title: 'March', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Months/March.mp4' },
          { id: 'april', title: 'April', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Months/April.mp4' },
          { id: 'may', title: 'May', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Months/May.mp4' },
          { id: 'june', title: 'June', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Months/June.mp4' },
          { id: 'july', title: 'July', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Months/July.mp4' },
          { id: 'august', title: 'August', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Months/August.mp4' },
          { id: 'september', title: 'September', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Months/Sept.mp4' },
          { id: 'october', title: 'October', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Months/Oct.mp4' },
          { id: 'november', title: 'November', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Months/Nov.mp4' },
          { id: 'december', title: 'December', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Months/Dec.mp4' },
          { id: 'today', title: 'Today', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Today.mp4' },
          { id: 'yesterday', title: 'Yesterday', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Yesterday.mp4' },
          { id: 'tomorrow', title: 'Tomorrow', video: '/FSLAssetsVideos/EeveryDayWords/daysOfTheWeek&Months/Tomorrow.mp4' },
        ]
      },
      colors: {
        title: 'Colors',
        description: 'Colors for describing objects and things',
        icon: '/SVGIcons/EveryDayWords/colors.svg',
        content: [
          { id: 'red', title: 'Red', video: '/FSLAssetsVideos/EeveryDayWords/colors/Red.mp4' },
          { id: 'blue', title: 'Blue', video: '/FSLAssetsVideos/EeveryDayWords/colors/Blue.mp4' },
          { id: 'green', title: 'Green', video: '/FSLAssetsVideos/EeveryDayWords/colors/Green.mp4' },
          { id: 'yellow', title: 'Yellow', video: '/FSLAssetsVideos/EeveryDayWords/colors/Yellow.mp4' },
          { id: 'orange', title: 'Orange', video: '/FSLAssetsVideos/EeveryDayWords/colors/Orange.mp4' },
          { id: 'purple', title: 'Purple', video: '/FSLAssetsVideos/EeveryDayWords/colors/Purple.mp4' },
          { id: 'pink', title: 'Pink', video: '/FSLAssetsVideos/EeveryDayWords/colors/Pink.mp4' },
          { id: 'black', title: 'Black', video: '/FSLAssetsVideos/EeveryDayWords/colors/Black.mp4' },
          { id: 'white', title: 'White', video: '/FSLAssetsVideos/EeveryDayWords/colors/White.mp4' },
          { id: 'gray', title: 'Gray', video: '/FSLAssetsVideos/EeveryDayWords/colors/Gray.mp4' },
          { id: 'brown', title: 'Brown', video: '/FSLAssetsVideos/EeveryDayWords/colors/Brown.mp4' },
        ]
      },
      family: {
        title: 'Family Members',
        description: 'Signs for family members',
        icon: '/SVGIcons/EveryDayWords/familyMembers.svg',
        content: [
          { id: 'father', title: 'Father', video: '/FSLAssetsVideos/EeveryDayWords/familyMembers/Father.mp4' },
          { id: 'mother', title: 'Mother', video: '/FSLAssetsVideos/EeveryDayWords/familyMembers/Mother.mp4' },
          { id: 'brother', title: 'Brother', video: '/FSLAssetsVideos/EeveryDayWords/familyMembers/Brother.mp4' },
          { id: 'sister', title: 'Sister', video: '/FSLAssetsVideos/EeveryDayWords/familyMembers/Sister.mp4' },
          { id: 'grandfather', title: 'Grandfather', video: '/FSLAssetsVideos/EeveryDayWords/familyMembers/Grandfather.mp4' },
          { id: 'grandmother', title: 'Grandmother', video: '/FSLAssetsVideos/EeveryDayWords/familyMembers/Grandmother.mp4' },
          { id: 'uncle', title: 'Uncle', video: '/FSLAssetsVideos/EeveryDayWords/familyMembers/Uncle.mp4' },
          { id: 'aunt', title: 'Aunt', video: '/FSLAssetsVideos/EeveryDayWords/familyMembers/Aunt.mp4' },
          { id: 'cousin', title: 'Cousin', video: '/FSLAssetsVideos/EeveryDayWords/familyMembers/Cousin.mp4' },
          { id: 'baby', title: 'Baby', video: '/FSLAssetsVideos/EeveryDayWords/familyMembers/Baby.mp4' },
        ]
      },
      objects: {
        title: 'Common Objects',
        description: 'Everyday objects and things',
        icon: '/SVGIcons/EveryDayWords/commonObjects.svg',
        content: [
          { id: 'book', title: 'Book', video: '/FSLAssetsVideos/EeveryDayWords/commonObjects/Book.mp4' },
          { id: 'pen', title: 'Pen', video: '/FSLAssetsVideos/EeveryDayWords/commonObjects/Pen.mp4' },
          { id: 'paper', title: 'Paper', video: '/FSLAssetsVideos/EeveryDayWords/commonObjects/Paper.mp4' },
          { id: 'bag', title: 'Bag', video: '/FSLAssetsVideos/EeveryDayWords/commonObjects/Bag.mp4' },
          { id: 'phone', title: 'Phone', video: '/FSLAssetsVideos/EeveryDayWords/commonObjects/Phone.mp4' },
          { id: 'chair', title: 'Chair', video: '/FSLAssetsVideos/EeveryDayWords/commonObjects/Chair.mp4' },
          { id: 'table', title: 'Table', video: '/FSLAssetsVideos/EeveryDayWords/commonObjects/Table.mp4' },
          { id: 'door', title: 'Door', video: '/FSLAssetsVideos/EeveryDayWords/commonObjects/Door.mp4' },
          { id: 'window', title: 'Window', video: '/FSLAssetsVideos/EeveryDayWords/commonObjects/Window.mp4' },
          { id: 'key', title: 'Key', video: '/FSLAssetsVideos/EeveryDayWords/commonObjects/Key.mp4' },
        ]
      },
      animals: {
        title: 'Animals',
        description: 'Common animals',
        icon: '/SVGIcons/EveryDayWords/animals.svg',
        content: [
          { id: 'dog', title: 'Dog', video: '/FSLAssetsVideos/EeveryDayWords/animals/Dog.mp4' },
          { id: 'cat', title: 'Cat', video: '/FSLAssetsVideos/EeveryDayWords/animals/Cat.mp4' },
          { id: 'bird', title: 'Bird', video: '/FSLAssetsVideos/EeveryDayWords/animals/Bird.mp4' },
          { id: 'fish', title: 'Fish', video: '/FSLAssetsVideos/EeveryDayWords/animals/Fish.mp4' },
          { id: 'cow', title: 'Cow', video: '/FSLAssetsVideos/EeveryDayWords/animals/Cow.mp4' },
          { id: 'pig', title: 'Pig', video: '/FSLAssetsVideos/EeveryDayWords/animals/Pig.mp4' },
          { id: 'horse', title: 'Horse', video: '/FSLAssetsVideos/EeveryDayWords/animals/Horse.mp4' },
          { id: 'chicken', title: 'Chicken', video: '/FSLAssetsVideos/EeveryDayWords/animals/Chicken.mp4' },
          { id: 'elephant', title: 'Elephant', video: '/FSLAssetsVideos/EeveryDayWords/animals/Elephant.mp4' },
          { id: 'tiger', title: 'Tiger', video: '/FSLAssetsVideos/EeveryDayWords/animals/Tiger.mp4' },
        ]
      },
      food: {
        title: 'Food & Drinks',
        description: 'Common foods and drinks',
        icon: '/SVGIcons/EveryDayWords/foodDrinks.svg',
        content: [
          { id: 'bread', title: 'Bread', video: '/FSLAssetsVideos/EeveryDayWords/Food&Drinks/Bread.mp4' },
          { id: 'coffee', title: 'Coffee', video: '/FSLAssetsVideos/EeveryDayWords/Food&Drinks/Coffee.mp4' },
          { id: 'egg', title: 'Egg', video: '/FSLAssetsVideos/EeveryDayWords/Food&Drinks/Egg.mp4' },
          { id: 'fish', title: 'Fish', video: '/FSLAssetsVideos/EeveryDayWords/Food&Drinks/Fish.mp4' },
          { id: 'fruit', title: 'Fruit', video: '/FSLAssetsVideos/EeveryDayWords/Food&Drinks/Fruit.mp4' },
          { id: 'meat', title: 'Meat', video: '/FSLAssetsVideos/EeveryDayWords/Food&Drinks/Meat.mp4' },
          { id: 'milk', title: 'Milk', video: '/FSLAssetsVideos/EeveryDayWords/Food&Drinks/Milk.mp4' },
          { id: 'rice', title: 'Rice', video: '/FSLAssetsVideos/EeveryDayWords/Food&Drinks/Rice.mp4' },
          { id: 'tea', title: 'Tea', video: '/FSLAssetsVideos/EeveryDayWords/Food&Drinks/Tea.mp4' },
          { id: 'vegetable', title: 'Vegetable', video: '/FSLAssetsVideos/EeveryDayWords/Food&Drinks/Vegetable.mp4' },
          { id: 'water', title: 'Water', video: '/FSLAssetsVideos/EeveryDayWords/Food&Drinks/Water.mp4' },
        ]
      },
      emotions: {
        title: 'Emotions & Feelings',
        description: 'Signs for emotions and feelings',
        icon: '/SVGIcons/EveryDayWords/emotions.svg',
        content: [
          { id: 'afraid', title: 'Afraid', video: '/FSLAssetsVideos/EeveryDayWords/Emotions&Feelings/Afraid.mp4' },
          { id: 'angry', title: 'Angry', video: '/FSLAssetsVideos/EeveryDayWords/Emotions&Feelings/Angry.mp4' },
          { id: 'bored', title: 'Bored', video: '/FSLAssetsVideos/EeveryDayWords/Emotions&Feelings/Bored.mp4' },
          { id: 'excited', title: 'Excited', video: '/FSLAssetsVideos/EeveryDayWords/Emotions&Feelings/Excited.mp4' },
          { id: 'happy', title: 'Happy', video: '/FSLAssetsVideos/EeveryDayWords/Emotions&Feelings/Happy.mp4' },
          { id: 'hungry', title: 'Hungry', video: '/FSLAssetsVideos/EeveryDayWords/Emotions&Feelings/Hungry.mp4' },
          { id: 'sad', title: 'Sad', video: '/FSLAssetsVideos/EeveryDayWords/Emotions&Feelings/Sad.mp4' },
          { id: 'sick', title: 'Sick', video: '/FSLAssetsVideos/EeveryDayWords/Emotions&Feelings/Sick.mp4' },
          { id: 'thirsty', title: 'Thirsty', video: '/FSLAssetsVideos/EeveryDayWords/Emotions&Feelings/Thirsty.mp4' },
          { id: 'tired', title: 'Tired', video: '/FSLAssetsVideos/EeveryDayWords/Emotions&Feelings/Tired.mp4' },
        ]
      },
      actions: {
        title: 'Basic Actions',
        description: 'Common action words',
        icon: '/SVGIcons/EveryDayWords/basicActions.svg',
        content: [
          { id: 'close', title: 'Close', video: '/FSLAssetsVideos/EeveryDayWords/basicActions/Close.mp4' },
          { id: 'drink', title: 'Drink', video: '/FSLAssetsVideos/EeveryDayWords/basicActions/Drink.mp4' },
          { id: 'eat', title: 'Eat', video: '/FSLAssetsVideos/EeveryDayWords/basicActions/Eat.mp4' },
          { id: 'open', title: 'Open', video: '/FSLAssetsVideos/EeveryDayWords/basicActions/Open.mp4' },
          { id: 'read', title: 'Read', video: '/FSLAssetsVideos/EeveryDayWords/basicActions/Read.mp4' },
          { id: 'run', title: 'Run', video: '/FSLAssetsVideos/EeveryDayWords/basicActions/Run.mp4' },
          { id: 'sit', title: 'Sit', video: '/FSLAssetsVideos/EeveryDayWords/basicActions/Sit.mp4' },
          { id: 'sleep', title: 'Sleep', video: '/FSLAssetsVideos/EeveryDayWords/basicActions/Sleep.mp4' },
          { id: 'stand', title: 'Stand', video: '/FSLAssetsVideos/EeveryDayWords/basicActions/Stand.mp4' },
          { id: 'walk', title: 'Walk', video: '/FSLAssetsVideos/EeveryDayWords/basicActions/Walk.mp4' },
          { id: 'write', title: 'Write', video: '/FSLAssetsVideos/EeveryDayWords/basicActions/Write.mp4' },
        ]
      },
      questions: {
        title: 'Question Words',
        description: 'Question words for asking information',
        icon: '/SVGIcons/EveryDayWords/questionWords.svg',
        content: [
          { id: 'how', title: 'How', video: '/FSLAssetsVideos/EeveryDayWords/questionWords/How.mp4' },
          { id: 'what', title: 'What', video: '/FSLAssetsVideos/EeveryDayWords/questionWords/What.mp4' },
          { id: 'when', title: 'When', video: '/FSLAssetsVideos/EeveryDayWords/questionWords/When.mp4' },
          { id: 'where', title: 'Where', video: '/FSLAssetsVideos/EeveryDayWords/questionWords/Where.mp4' },
          { id: 'which', title: 'Which', video: '/FSLAssetsVideos/EeveryDayWords/questionWords/Which.mp4' },
          { id: 'who', title: 'Who', video: '/FSLAssetsVideos/EeveryDayWords/questionWords/Who.mp4' },
          { id: 'whose', title: 'Whose', video: '/FSLAssetsVideos/EeveryDayWords/questionWords/Whose.mp4' },
          { id: 'why', title: 'Why', video: '/FSLAssetsVideos/EeveryDayWords/questionWords/Why.mp4' },
        ]
      },
      places: {
        title: 'Places',
        description: 'Common places',
        icon: '/SVGIcons/EveryDayWords/places.svg',
        content: [
          { id: 'bank', title: 'Bank', video: '/FSLAssetsVideos/EeveryDayWords/places/Bank.mp4' },
          { id: 'church', title: 'Church', video: '/FSLAssetsVideos/EeveryDayWords/places/Church.mp4' },
          { id: 'home', title: 'Home', video: '/FSLAssetsVideos/EeveryDayWords/places/Home.mp4' },
          { id: 'hospital', title: 'Hospital', video: '/FSLAssetsVideos/EeveryDayWords/places/Hospital.mp4' },
          { id: 'mall', title: 'Mall', video: '/FSLAssetsVideos/EeveryDayWords/places/Mall.mp4' },
          { id: 'market', title: 'Market', video: '/FSLAssetsVideos/EeveryDayWords/places/Market.mp4' },
          { id: 'park', title: 'Park', video: '/FSLAssetsVideos/EeveryDayWords/places/Park.mp4' },
          { id: 'restaurant', title: 'Restaurant', video: '/FSLAssetsVideos/EeveryDayWords/places/Restaurant.mp4' },
          { id: 'school', title: 'School', video: '/FSLAssetsVideos/EeveryDayWords/places/School.mp4' },
          { id: 'store', title: 'Store', video: '/FSLAssetsVideos/EeveryDayWords/places/Store.mp4' },
        ]
      },
      timeWeather: {
        title: 'Time & Weather',
        description: 'Time and weather expressions',
        icon: '/SVGIcons/EveryDayWords/timeWeather.svg',
        content: [
          { id: 'afternoon', title: 'Afternoon', video: '/FSLAssetsVideos/EeveryDayWords/time&weather/Afternoon.mp4' },
          { id: 'cold', title: 'Cold', video: '/FSLAssetsVideos/EeveryDayWords/time&weather/Cold.mp4' },
          { id: 'evening', title: 'Evening', video: '/FSLAssetsVideos/EeveryDayWords/time&weather/Evening.mp4' },
          { id: 'hot', title: 'Hot', video: '/FSLAssetsVideos/EeveryDayWords/time&weather/Hot.mp4' },
          { id: 'morning', title: 'Morning', video: '/FSLAssetsVideos/EeveryDayWords/time&weather/Morning.mp4' },
          { id: 'night', title: 'Night', video: '/FSLAssetsVideos/EeveryDayWords/time&weather/Night.mp4' },
          { id: 'rain', title: 'Rain', video: '/FSLAssetsVideos/EeveryDayWords/time&weather/Rain.mp4' },
          { id: 'snow', title: 'Snow', video: '/FSLAssetsVideos/EeveryDayWords/time&weather/Snow.mp4' },
          { id: 'sun', title: 'Sun', video: '/FSLAssetsVideos/EeveryDayWords/time&weather/Sun.mp4' },
          { id: 'wind', title: 'Wind', video: '/FSLAssetsVideos/EeveryDayWords/time&weather/Wind.mp4' },
        ]
      },
      body: {
        title: 'Body Parts',
        description: 'Signs for body parts',
        icon: '/SVGIcons/EveryDayWords/bodyparts.svg',
        content: [
          { id: 'arms', title: 'Arms', video: '/FSLAssetsVideos/EeveryDayWords/bodyParts/Arms.mp4' },
          { id: 'ears', title: 'Ears', video: '/FSLAssetsVideos/EeveryDayWords/bodyParts/Ears.mp4' },
          { id: 'eyes', title: 'Eyes', video: '/FSLAssetsVideos/EeveryDayWords/bodyParts/Eyes.mp4' },
          { id: 'feet', title: 'Feet', video: '/FSLAssetsVideos/EeveryDayWords/bodyParts/Feet.mp4' },
          { id: 'hands', title: 'Hands', video: '/FSLAssetsVideos/EeveryDayWords/bodyParts/Hands.mp4' },
          { id: 'head', title: 'Head', video: '/FSLAssetsVideos/EeveryDayWords/bodyParts/Head.mp4' },
          { id: 'legs', title: 'Legs', video: '/FSLAssetsVideos/EeveryDayWords/bodyParts/Legs.mp4' },
          { id: 'mouth', title: 'Mouth', video: '/FSLAssetsVideos/EeveryDayWords/bodyParts/Mouth.mp4' },
          { id: 'nose', title: 'Nose', video: '/FSLAssetsVideos/EeveryDayWords/bodyParts/Nose.mp4' },
          { id: 'stomach', title: 'Stomach', video: '/FSLAssetsVideos/EeveryDayWords/bodyParts/Stomach.mp4' },
        ]
      },
      transport: {
        title: 'Transportation & Directions',
        description: 'Transportation and direction words',
        icon: '/SVGIcons/EveryDayWords/transportationDirection.svg',
        content: [
          { id: 'airplane', title: 'Airplane', video: '/FSLAssetsVideos/EeveryDayWords/transportation/Airplane.mp4' },
          { id: 'bicycle', title: 'Bicycle', video: '/FSLAssetsVideos/EeveryDayWords/transportation/Bicycle.mp4' },
          { id: 'boat', title: 'Boat', video: '/FSLAssetsVideos/EeveryDayWords/transportation/Boat.mp4' },
          { id: 'bus', title: 'Bus', video: '/FSLAssetsVideos/EeveryDayWords/transportation/Bus.mp4' },
          { id: 'car', title: 'Car', video: '/FSLAssetsVideos/EeveryDayWords/transportation/Car.mp4' },
          { id: 'go', title: 'Go', video: '/FSLAssetsVideos/EeveryDayWords/transportation/Go.mp4' },
          { id: 'left', title: 'Left', video: '/FSLAssetsVideos/EeveryDayWords/transportation/Left.mp4' },
          { id: 'right', title: 'Right', video: '/FSLAssetsVideos/EeveryDayWords/transportation/Right.mp4' },
          { id: 'stop', title: 'Stop', video: '/FSLAssetsVideos/EeveryDayWords/transportation/Stop.mp4' },
          { id: 'straight', title: 'Straight', video: '/FSLAssetsVideos/EeveryDayWords/transportation/Straight.mp4' },
        ]
      },
    }
  },
  additionalBasics: {
    title: 'Additional Basics',
    description: 'Expands on everyday communication with more specialized vocabulary for practical use.',
    icon: '/SVGIcons/AddtionalBasic/pronouns.svg',
    gradient: 'linear-gradient(135deg, #f953c6 0%, #b91d73 100%)',
    totalSigns: 131,
    subCategories: {
      pronouns: {
        title: 'Pronouns',
        description: 'Personal and group pronouns',
        icon: '/SVGIcons/AddtionalBasic/pronouns.svg',
        content: [
          { id: 'he', title: 'He', video: '/FSLAssetsVideos/AdditionalBasics/pronouns/He.mp4' },
          { id: 'her', title: 'Her', video: '/FSLAssetsVideos/AdditionalBasics/pronouns/Her.mp4' },
          { id: 'him', title: 'Him', video: '/FSLAssetsVideos/AdditionalBasics/pronouns/Him.mp4' },
          { id: 'i', title: 'I', video: '/FSLAssetsVideos/AdditionalBasics/pronouns/I.mp4' },
          { id: 'me', title: 'Me', video: '/FSLAssetsVideos/AdditionalBasics/pronouns/Me.mp4' },
          { id: 'she', title: 'She', video: '/FSLAssetsVideos/AdditionalBasics/pronouns/She.mp4' },
          { id: 'them', title: 'Them', video: '/FSLAssetsVideos/AdditionalBasics/pronouns/Them.mp4' },
          { id: 'they', title: 'They', video: '/FSLAssetsVideos/AdditionalBasics/pronouns/They.mp4' },
          { id: 'us', title: 'Us', video: '/FSLAssetsVideos/AdditionalBasics/pronouns/Us.mp4' },
          { id: 'we', title: 'We', video: '/FSLAssetsVideos/AdditionalBasics/pronouns/We.mp4' },
          { id: 'you', title: 'You', video: '/FSLAssetsVideos/AdditionalBasics/pronouns/You.mp4' },
        ]
      },
      verbs: {
        title: 'Common Verbs',
        description: 'Frequently used verbs',
        icon: '/SVGIcons/AddtionalBasic/commonVerbs.svg',
        content: [
          { id: 'bring', title: 'Bring', video: '/FSLAssetsVideos/AdditionalBasics/commonVerbs/Bring.mp4' },
          { id: 'buy', title: 'Buy', video: '/FSLAssetsVideos/AdditionalBasics/commonVerbs/Buy.mp4' },
          { id: 'call', title: 'Call', video: '/FSLAssetsVideos/AdditionalBasics/commonVerbs/Call.mp4' },
          { id: 'give', title: 'Give', video: '/FSLAssetsVideos/AdditionalBasics/commonVerbs/Give.mp4' },
          { id: 'have', title: 'Have', video: '/FSLAssetsVideos/AdditionalBasics/commonVerbs/Have.mp4' },
          { id: 'need', title: 'Need', video: '/FSLAssetsVideos/AdditionalBasics/commonVerbs/Need.mp4' },
          { id: 'sell', title: 'Sell', video: '/FSLAssetsVideos/AdditionalBasics/commonVerbs/Sell.mp4' },
          { id: 'take', title: 'Take', video: '/FSLAssetsVideos/AdditionalBasics/commonVerbs/Take.mp4' },
          { id: 'wait', title: 'Wait', video: '/FSLAssetsVideos/AdditionalBasics/commonVerbs/Wait.mp4' },
          { id: 'want', title: 'Want', video: '/FSLAssetsVideos/AdditionalBasics/commonVerbs/Want.mp4' },
        ]
      },
      opposites: {
        title: 'Opposites',
        description: 'Common opposites for comparison',
        icon: '/SVGIcons/AddtionalBasic/opposites.svg',
        content: [
          { id: 'big-small', title: 'Big & Small', video: '/FSLAssetsVideos/AdditionalBasics/opposites/Big-Small.mp4' },
          { id: 'fast-slow', title: 'Fast & Slow', video: '/FSLAssetsVideos/AdditionalBasics/opposites/Fast-Slow.mp4' },
          { id: 'hard-soft', title: 'Hard & Soft', video: '/FSLAssetsVideos/AdditionalBasics/opposites/Hard-Soft.mp4' },
          { id: 'hot-cold', title: 'Hot & Cold', video: '/FSLAssetsVideos/AdditionalBasics/opposites/Hot-Cold.mp4' },
          { id: 'light-dark', title: 'Light & Dark', video: '/FSLAssetsVideos/AdditionalBasics/opposites/Light-Dark.mp4' },
          { id: 'near-far', title: 'Near & Far', video: '/FSLAssetsVideos/AdditionalBasics/opposites/Near-Far.mp4' },
          { id: 'old-young', title: 'Old & Young', video: '/FSLAssetsVideos/AdditionalBasics/opposites/Old-Young.mp4' },
          { id: 'open-close', title: 'Open & Close', video: '/FSLAssetsVideos/AdditionalBasics/opposites/Open-Close.mp4' },
          { id: 'thick-thin', title: 'Thick & Thin', video: '/FSLAssetsVideos/AdditionalBasics/opposites/Thick-Thin.mp4' },
          { id: 'up-down', title: 'Up & Down', video: '/FSLAssetsVideos/AdditionalBasics/opposites/Up-Down.mp4' },
        ]
      },
      shapes: {
        title: 'Shapes & Sizes',
        description: 'Shapes and size-related words',
        icon: '/SVGIcons/AddtionalBasic/shapesSizes.svg',
        content: [
          { id: 'circle', title: 'Circle', video: '/FSLAssetsVideos/AdditionalBasics/shapeAndSizes/Circle.mp4' },
          { id: 'deep', title: 'Deep', video: '/FSLAssetsVideos/AdditionalBasics/shapeAndSizes/Deep.mp4' },
          { id: 'long', title: 'Long', video: '/FSLAssetsVideos/AdditionalBasics/shapeAndSizes/Long.mp4' },
          { id: 'narrow', title: 'Narrow', video: '/FSLAssetsVideos/AdditionalBasics/shapeAndSizes/Narrow.mp4' },
          { id: 'rectangle', title: 'Rectangle', video: '/FSLAssetsVideos/AdditionalBasics/shapeAndSizes/Rectangle.mp4' },
          { id: 'short', title: 'Short', video: '/FSLAssetsVideos/AdditionalBasics/shapeAndSizes/Short.mp4' },
          { id: 'square', title: 'Square', video: '/FSLAssetsVideos/AdditionalBasics/shapeAndSizes/Square.mp4' },
          { id: 'tall', title: 'Tall', video: '/FSLAssetsVideos/AdditionalBasics/shapeAndSizes/Tall.mp4' },
          { id: 'triangle', title: 'Triangle', video: '/FSLAssetsVideos/AdditionalBasics/shapeAndSizes/Triangle.mp4' },
          { id: 'wide', title: 'Wide', video: '/FSLAssetsVideos/AdditionalBasics/shapeAndSizes/Wide.mp4' },
        ]
      },
      household: {
        title: 'Common Household Items',
        description: 'Household items and objects',
        icon: '/SVGIcons/AddtionalBasic/commonHousehold.svg',
        content: [
          { id: 'blanket', title: 'Blanket', video: '/FSLAssetsVideos/AdditionalBasics/commonHouseholdItems/Blanket.mp4' },
          { id: 'cup', title: 'Cup', video: '/FSLAssetsVideos/AdditionalBasics/commonHouseholdItems/Cup.mp4' },
          { id: 'fork', title: 'Fork', video: '/FSLAssetsVideos/AdditionalBasics/commonHouseholdItems/Fork.mp4' },
          { id: 'pan', title: 'Pan', video: '/FSLAssetsVideos/AdditionalBasics/commonHouseholdItems/Pan.mp4' },
          { id: 'pillow', title: 'Pillow', video: '/FSLAssetsVideos/AdditionalBasics/commonHouseholdItems/Pillow.mp4' },
          { id: 'plate', title: 'Plate', video: '/FSLAssetsVideos/AdditionalBasics/commonHouseholdItems/Plate.mp4' },
          { id: 'pot', title: 'Pot', video: '/FSLAssetsVideos/AdditionalBasics/commonHouseholdItems/Pot.mp4' },
          { id: 'soap', title: 'Soap', video: '/FSLAssetsVideos/AdditionalBasics/commonHouseholdItems/Soap.mp4' },
          { id: 'spoon', title: 'Spoon', video: '/FSLAssetsVideos/AdditionalBasics/commonHouseholdItems/Spoon.mp4' },
          { id: 'towel', title: 'Towel', video: '/FSLAssetsVideos/AdditionalBasics/commonHouseholdItems/Towel.mp4' },
        ]
      },
      communication: {
        title: 'Modes of Communication',
        description: 'Ways to communicate',
        icon: '/SVGIcons/AddtionalBasic/communication.svg',
        content: [
          { id: 'call', title: 'Call', video: '/FSLAssetsVideos/AdditionalBasics/modesOfCommunication/Call.mp4' },
          { id: 'email', title: 'Email', video: '/FSLAssetsVideos/AdditionalBasics/modesOfCommunication/Email.mp4' },
          { id: 'listen', title: 'Listen', video: '/FSLAssetsVideos/AdditionalBasics/modesOfCommunication/Listen.mp4' },
          { id: 'message', title: 'Message', video: '/FSLAssetsVideos/AdditionalBasics/modesOfCommunication/Message.mp4' },
          { id: 'read', title: 'Read', video: '/FSLAssetsVideos/AdditionalBasics/modesOfCommunication/Read.mp4' },
          { id: 'sign', title: 'Sign', video: '/FSLAssetsVideos/AdditionalBasics/modesOfCommunication/Sign.mp4' },
          { id: 'talk', title: 'Talk', video: '/FSLAssetsVideos/AdditionalBasics/modesOfCommunication/Talk.mp4' },
          { id: 'text', title: 'Text', video: '/FSLAssetsVideos/AdditionalBasics/modesOfCommunication/Text.mp4' },
          { id: 'watch', title: 'Watch', video: '/FSLAssetsVideos/AdditionalBasics/modesOfCommunication/Watch.mp4' },
          { id: 'write', title: 'Write', video: '/FSLAssetsVideos/AdditionalBasics/modesOfCommunication/Write.mp4' },
        ]
      },
      clothing: {
        title: 'Clothing & Accessories',
        description: 'Clothing and accessories',
        icon: '/SVGIcons/AddtionalBasic/clothingAccesories.svg',
        content: [
          { id: 'bag', title: 'Bag', video: '/FSLAssetsVideos/AdditionalBasics/clothingAndAccessories/Bag.mp4' },
          { id: 'dress', title: 'Dress', video: '/FSLAssetsVideos/AdditionalBasics/clothingAndAccessories/Dress.mp4' },
          { id: 'glasses', title: 'Glasses', video: '/FSLAssetsVideos/AdditionalBasics/clothingAndAccessories/Glasses.mp4' },
          { id: 'hat', title: 'Hat', video: '/FSLAssetsVideos/AdditionalBasics/clothingAndAccessories/Hat.mp4' },
          { id: 'jacket', title: 'Jacket', video: '/FSLAssetsVideos/AdditionalBasics/clothingAndAccessories/Jacket.mp4' },
          { id: 'pants', title: 'Pants', video: '/FSLAssetsVideos/AdditionalBasics/clothingAndAccessories/Pants.mp4' },
          { id: 'ring', title: 'Ring', video: '/FSLAssetsVideos/AdditionalBasics/clothingAndAccessories/Ring.mp4' },
          { id: 'shirt', title: 'Shirt', video: '/FSLAssetsVideos/AdditionalBasics/clothingAndAccessories/Shirt.mp4' },
          { id: 'shoes', title: 'Shoes', video: '/FSLAssetsVideos/AdditionalBasics/clothingAndAccessories/Shoes.mp4' },
          { id: 'socks', title: 'Socks', video: '/FSLAssetsVideos/AdditionalBasics/clothingAndAccessories/Socks.mp4' },
        ]
      },
      payment: {
        title: 'Modes of Payment',
        description: 'Payment methods and related words',
        icon: '/SVGIcons/AddtionalBasic/modesOf Payment.svg',
        content: [
          { id: 'buy', title: 'Buy', video: '/FSLAssetsVideos/AdditionalBasics/modesOfPayment/Buy.mp4' },
          { id: 'card', title: 'Card', video: '/FSLAssetsVideos/AdditionalBasics/modesOfPayment/Card.mp4' },
          { id: 'cash', title: 'Cash', video: '/FSLAssetsVideos/AdditionalBasics/modesOfPayment/Cash.mp4' },
          { id: 'change', title: 'Change', video: '/FSLAssetsVideos/AdditionalBasics/modesOfPayment/Charge.mp4' },
          { id: 'cheap', title: 'Cheap', video: '/FSLAssetsVideos/AdditionalBasics/modesOfPayment/Cheap.mp4' },
          { id: 'coins', title: 'Coins', video: '/FSLAssetsVideos/AdditionalBasics/modesOfPayment/Coins.mp4' },
          { id: 'expensive', title: 'Expensive', video: '/FSLAssetsVideos/AdditionalBasics/modesOfPayment/Expensive.mp4' },
          { id: 'pay', title: 'Pay', video: '/FSLAssetsVideos/AdditionalBasics/modesOfPayment/Pay.mp4' },
          { id: 'sell', title: 'Sell', video: '/FSLAssetsVideos/AdditionalBasics/modesOfPayment/Sell.mp4' },
          { id: 'wallet', title: 'Wallet', video: '/FSLAssetsVideos/AdditionalBasics/modesOfPayment/Wallet.mp4' },
        ]
      },
      social: {
        title: 'Social Relationships',
        description: 'Words for social relationships and politeness',
        icon: '/SVGIcons/AddtionalBasic/socialRelationship.svg',
        content: [
          { id: 'family', title: 'Family', video: '/FSLAssetsVideos/AdditionalBasics/socialRelationship/Family.mp4' },
          { id: 'friend', title: 'Friend', video: '/FSLAssetsVideos/AdditionalBasics/socialRelationship/Friend.mp4' },
          { id: 'help', title: 'Help', video: '/FSLAssetsVideos/AdditionalBasics/socialRelationship/Help.mp4' },
          { id: 'love', title: 'Love', video: '/FSLAssetsVideos/AdditionalBasics/socialRelationship/Love.mp4' },
          { id: 'no', title: 'No', video: '/FSLAssetsVideos/AdditionalBasics/socialRelationship/No.mp4' },
          { id: 'please', title: 'Please', video: '/FSLAssetsVideos/AdditionalBasics/socialRelationship/Please.mp4' },
          { id: 'respect', title: 'Respect', video: '/FSLAssetsVideos/AdditionalBasics/socialRelationship/Respect.mp4' },
          { id: 'sorry', title: 'Sorry', video: '/FSLAssetsVideos/AdditionalBasics/socialRelationship/Sorry.mp4' },
          { id: 'thankyou', title: 'Thank you', video: '/FSLAssetsVideos/AdditionalBasics/socialRelationship/Thankyou.mp4' },
          { id: 'yes', title: 'Yes', video: '/FSLAssetsVideos/AdditionalBasics/socialRelationship/Yes.mp4' },
        ]
      },
      emergency: {
        title: 'Emergency Signs',
        description: 'Signs for emergencies and urgent situations',
        icon: '/SVGIcons/AddtionalBasic/emergencySigns.svg',
        content: [
          { id: 'call', title: 'Call', video: '/FSLAssetsVideos/AdditionalBasics/emergencySigns/Call.mp4' },
          { id: 'danger', title: 'Danger', video: '/FSLAssetsVideos/AdditionalBasics/emergencySigns/Danger.mp4' },
          { id: 'doctor', title: 'Doctor', video: '/FSLAssetsVideos/AdditionalBasics/emergencySigns/Doctor.mp4' },
          { id: 'fire', title: 'Fire', video: '/FSLAssetsVideos/AdditionalBasics/emergencySigns/Fire.mp4' },
          { id: 'go', title: 'Go', video: '/FSLAssetsVideos/AdditionalBasics/emergencySigns/Go.mp4' },
          { id: 'police', title: 'Police', video: '/FSLAssetsVideos/AdditionalBasics/emergencySigns/Police.mp4' },
          { id: 'run', title: 'Run', video: '/FSLAssetsVideos/AdditionalBasics/emergencySigns/Run.mp4' },
          { id: 'stop', title: 'Stop', video: '/FSLAssetsVideos/AdditionalBasics/emergencySigns/Stop.mp4' },
        ]
      },
      prepositions: {
        title: 'Prepositions & Locations',
        description: 'Prepositions and location words',
        icon: '/SVGIcons/AddtionalBasic/preopositionAndlLocations.svg',
        content: [
          { id: 'above', title: 'Above', video: '/FSLAssetsVideos/AdditionalBasics/prepositionsAndLocation/Above.mp4' },
          { id: 'behind', title: 'Behind', video: '/FSLAssetsVideos/AdditionalBasics/prepositionsAndLocation/Behind.mp4' },
          { id: 'below', title: 'Below', video: '/FSLAssetsVideos/AdditionalBasics/prepositionsAndLocation/Below.mp4' },
          { id: 'beside', title: 'Beside', video: '/FSLAssetsVideos/AdditionalBasics/prepositionsAndLocation/Beside.mp4' },
          { id: 'between', title: 'Between', video: '/FSLAssetsVideos/AdditionalBasics/prepositionsAndLocation/Between.mp4' },
          { id: 'far', title: 'Far', video: '/FSLAssetsVideos/AdditionalBasics/prepositionsAndLocation/Far.mp4' },
          { id: 'infront', title: 'In Front', video: '/FSLAssetsVideos/AdditionalBasics/prepositionsAndLocation/Infront.mp4' },
          { id: 'inside', title: 'Inside', video: '/FSLAssetsVideos/AdditionalBasics/prepositionsAndLocation/Inside.mp4' },
          { id: 'near', title: 'Near', video: '/FSLAssetsVideos/AdditionalBasics/prepositionsAndLocation/Near.mp4' },
          { id: 'outside', title: 'Outside', video: '/FSLAssetsVideos/AdditionalBasics/prepositionsAndLocation/Outside.mp4' },
        ]
      },
      commands: {
        title: 'Basic Commands',
        description: 'Basic commands and instructions',
        icon: '/SVGIcons/AddtionalBasic/basicCommands.svg',
        content: [
          { id: 'come', title: 'Come', video: '/FSLAssetsVideos/AdditionalBasics/basicCommands/Come.mp4' },
          { id: 'follow', title: 'Follow', video: '/FSLAssetsVideos/AdditionalBasics/basicCommands/Follow.mp4' },
          { id: 'go', title: 'Go', video: '/FSLAssetsVideos/AdditionalBasics/basicCommands/Go.mp4' },
          { id: 'listen', title: 'Listen', video: '/FSLAssetsVideos/AdditionalBasics/basicCommands/Listen.mp4' },
          { id: 'look', title: 'Look', video: '/FSLAssetsVideos/AdditionalBasics/basicCommands/Look.mp4' },
          { id: 'sit', title: 'Sit', video: '/FSLAssetsVideos/AdditionalBasics/basicCommands/Sit.mp4' },
          { id: 'stand', title: 'Stand', video: '/FSLAssetsVideos/AdditionalBasics/basicCommands/Stand.mp4' },
          { id: 'stay', title: 'Stay', video: '/FSLAssetsVideos/AdditionalBasics/basicCommands/Stay.mp4' },
          { id: 'stop', title: 'Stop', video: '/FSLAssetsVideos/AdditionalBasics/basicCommands/Stop.mp4' },
          { id: 'wait', title: 'Wait', video: '/FSLAssetsVideos/AdditionalBasics/basicCommands/Wait.mp4' },
        ]
      },
    }
  }
}; 